name: Build

on: [push]

jobs:
  build:
    name: Action CI
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo gem install standard
      shell: bash
    - uses: actions/checkout@v1
    - name: Verify action syntax
      # The action should not publish any real changes, but should succeed.
      uses: './'
      with:
        use-bundler: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
